# Generated by Django 4.2.4 on 2023-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Saturated Fat (g)'),
        ),
    ]
