# Generated by Django 4.2.4 on 2023-08-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_saturated_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=0, verbose_name='Cholesterol (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(default=0, verbose_name='Dietary Fibre (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0, verbose_name='Protein (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0, verbose_name='Sodium (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=0, verbose_name='Sugar (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='total_carbohydrate',
            field=models.FloatField(default=0, verbose_name='Total Carbohydrate (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(default=0, verbose_name='Saturated Fat (g)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Morning Snack'), (3, 'Lunch'), (4, 'Afternoon Snack'), (5, 'Dinner'), (6, 'Evening Snack')], verbose_name='Meal Time'),
        ),
    ]
